apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: passman
spec:
  ports:
  - port: 27017
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: db-svc
  namespace: passman
subsets:
  - addresses:
    - ip: 10.105.26.17
    ports:
    - port: 27017